package com.vbronshtein.couponSystem.couponsystemderby.beans;


import javax.xml.bind.annotation.XmlRootElement;
import java.util.Collection;

/**
 * Customer bean ( Template of Customer Object ).
 *
 * @author vbronshtein
 *
 */
@XmlRootElement
public class Customer {
    private long id;
    private String custName;
    private String password;
    private Collection<Coupon> coupons;

    /**
     * Default Constructor
     */
    public Customer() {
        super();
    }

    /**
     * Full Customer constructor ( for new Customer fast creation )
     *
     * @param custName
     *            Customer name.
     * @param password
     *            Password for login to Customer user.
     */
    public Customer(String custName, String password) {
        super();
        this.custName = custName;
        this.password = password;
    }

    /**
     * Get Customer Id
     *
     * @return id - Customer Id
     */
    public long getId() {
        return id;
    }

    /**
     * Set Customer Id
     *
     * @param id
     *            Customer Id , auto generated by DB.
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Get Customer name
     *
     * @return custName - Customer name
     */
    public String getCustName() {
        return custName;
    }

    /**
     * Set Customer name
     *
     * @param custName
     *            Customer name.
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * Get Customer password
     *
     * @return password - Customer password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set Customer password
     *
     * @param password
     *            Password for login to Customer user.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get Customer Coupons
     *
     * @return coupons - Collection of Customer coupons
     */
    public Collection<Coupon> getCoupons() {
        return coupons;
    }

    /**
     * Set Customer coupons
     *
     * @param coupons
     *            List of Client Coupons.
     */
    public void setCoupons(Collection<Coupon> coupons) {
        this.coupons = coupons;
    }

    @Override
    public String toString() {
        return "Customer [id=" + id + ", custName=" + custName + ", password=" + password + ", coupons=" + coupons
                + "]";
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((custName == null) ? 0 : custName.hashCode());
        return result;
    }

    public boolean isNameEqualTo(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Customer other = (Customer) obj;
        if (custName == null) {
            if (other.custName != null)
                return false;
        } else if (!custName.equals(other.custName))
            return false;
        return true;
    }

}
